language: minimal

git:
  depth: 1

install: scripts/install.sh
script:
  - scripts/run_tests.sh
  - scripts/run_regen_docs.sh
  - scripts/run_buildifier.sh

matrix:
  include:
    - os: linux
      env:
        - INSTALL_BAZEL=HEAD
        - RUN_TESTS=1
    - os: linux
      env:
        - INSTALL_BAZEL=RELEASE
        - RUN_TESTS=1
        - RUN_REGEN_DOCS=1
        - RUN_BUILDIFIER=1
